var dados = {
"presentes": [
{
"item": "Corrida de Kart",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 130,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Kartódromo Aldeia da Serra",
"endereco": "Estrada Doutor Yojiro Takaoka, 88",
"telefone": "(11) 4619 4682",
"bairro": "Jardim Itaquiti",
"link": "http://vejasp.abril.com.br/estabelecimento/kartodromo-aldeia-da-serra",
"top3": "não",
"imagem": "kart"
},
{
"item": "Corrida de Kart",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 130,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Kartódromo Aldeia da Serra",
"endereco": "Estrada Doutor Yojiro Takaoka, 88",
"telefone": "(11) 4619 4682",
"bairro": "Jardim Itaquiti",
"link": "http://vejasp.abril.com.br/estabelecimento/kartodromo-aldeia-da-serra",
"top3": "não",
"imagem": "kart"
},
{
"item": "Escalada Indoor",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 30,00",
"preco": "até R$ 100,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "90 Graus",
"endereco": "Avenida João Pedro Cardoso, 107",
"telefone": "(11) 5034 8775",
"bairro": "Parque Jabaquara",
"link": "http://vejasp.abril.com.br/estabelecimento/90-graus",
"top3": "sim",
"imagem": "escalada"
},
{
"item": "Escalada Indoor",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 30,00",
"preco": "até R$ 100,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "90 Graus",
"endereco": "Avenida João Pedro Cardoso, 107",
"telefone": "(11) 5034 8775",
"bairro": "Parque Jabaquara",
"link": "http://vejasp.abril.com.br/estabelecimento/90-graus",
"top3": "sim",
"imagem": "escalada"
},
{
"item": "Day Spa para o Casal",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 315,00",
"preco": "acima de R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Espaço Girassol",
"endereco": "Rua Fradique Coutinho, 1190",
"telefone": "(11) 2925 9000",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/espaco-girassol-spa-yoga",
"top3": "não",
"imagem": "day-spa"
},
{
"item": "Day Spa para o Casal",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 315,00",
"preco": "acima de R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Espaço Girassol",
"endereco": "Rua Fradique Coutinho, 1190",
"telefone": "(11) 2925 9000",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/espaco-girassol-spa-yoga",
"top3": "não",
"imagem": "day-spa"
},
{
"item": "Paraquedismo",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 410,00",
"preco": "acima de R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Hangar Vera Cruz",
"endereco": "Acesso de Campinas pela SP 340/344",
"telefone": "(19) 3246-0455",
"bairro": "São João da Boavista",
"link": "http://vejasp.abril.com.br/atracao/paraquedismo",
"top3": "sim",
"imagem": "paraquedismo"
},
{
"item": "Paraquedismo",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 410,00",
"preco": "acima de R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Hangar Vera Cruz",
"endereco": "Acesso de Campinas pela SP 340/344",
"telefone": "(19) 3246-0455",
"bairro": "São João da Boavista",
"link": "http://vejasp.abril.com.br/atracao/paraquedismo",
"top3": "sim",
"imagem": "paraquedismo"
},
{
"item": "Jun Sakamoto",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Jun Sakamoto",
"endereco": "Rua Lisboa, 55",
"telefone": "(11) 3088 6019",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/jun-sakamoto",
"top3": "sim",
"imagem": "jun-sakamoto"
},
{
"item": "Kinu",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Kinu",
"endereco": "Avenida das Nações Unidas, 13301 - Grand Hyatt São Paulo",
"telefone": "(11) 2838 3208",
"bairro": "Brooklin Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/kinu",
"top3": "não",
"imagem": "kinu-restaurante"
},
{
"item": "Aizomê",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Aizomê",
"endereco": "Alameda Fernão Cardim, 39",
"telefone": "(11) 3251 5157",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/aizome",
"top3": "não",
"imagem": "aizome-restaurante"
},
{
"item": "La Paillote - Jardim Paulista",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "La Paillote - Jardim Paulista",
"endereco": "Rua Doutor Melo Alves, 769",
"telefone": "(11) 5063 3737",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/la-paillote-jardim-paulista",
"top3": "não",
"imagem": "la-paillote"
},
{
"item": "Freddy",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Freddy",
"endereco": "Rua Pedroso Alvarenga, 1170",
"telefone": "(11) 3167 0977",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/freddy",
"top3": "não",
"imagem": "freddy"
},
{
"item": "Fasano",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Fasano",
"endereco": "Rua Vitório Fasano, 88",
"telefone": "(11) 3062 4000",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/fasano",
"top3": "sim",
"imagem": "fasano"
},
{
"item": "Terraço Itália",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Terraço Itália",
"endereco": "Avenida Ipiranga, 344",
"telefone": "(11) 2189 2929",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/terraco-italia",
"top3": "sim",
"imagem": "terraco-italia"
},
{
"item": "Jun Sakamoto",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Jun Sakamoto",
"endereco": "Rua Lisboa, 55",
"telefone": "(11) 3088 6019",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/jun-sakamoto",
"top3": "sim",
"imagem": "jun-sakamoto"
},
{
"item": "Kinu",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Kinu",
"endereco": "Avenida das Nações Unidas, 13301 - Grand Hyatt São Paulo",
"telefone": "(11) 2838 3208",
"bairro": "Brooklin Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/kinu",
"top3": "não",
"imagem": "kinu-restaurante"
},
{
"item": "Aizomê",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Aizomê",
"endereco": "Alameda Fernão Cardim, 39",
"telefone": "(11) 3251 5157",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/aizome",
"top3": "não",
"imagem": "aizome-restaurante"
},
{
"item": "La Paillote - Jardim Paulista",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "La Paillote - Jardim Paulista",
"endereco": "Rua Doutor Melo Alves, 769",
"telefone": "(11) 5063 3737",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/la-paillote-jardim-paulista",
"top3": "não",
"imagem": "la-paillote"
},
{
"item": "Freddy",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Freddy",
"endereco": "Rua Pedroso Alvarenga, 1170",
"telefone": "(11) 3167 0977",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/freddy",
"top3": "não",
"imagem": "freddy"
},
{
"item": "Fasano",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Fasano",
"endereco": "Rua Vitório Fasano, 88",
"telefone": "(11) 3062 4000",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/fasano",
"top3": "sim",
"imagem": "fasano"
},
{
"item": "Terraço Itália",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Terraço Itália",
"endereco": "Avenida Ipiranga, 344",
"telefone": "(11) 2189 2929",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/terraco-italia",
"top3": "sim",
"imagem": "terraco-italia"
},
{
"item": "Tian",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "até R$ 70,00",
"preco": "até R$ 70,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Tian",
"endereco": "Rua Jerônimo da Veiga, 36",
"telefone": "(11) 2389 9399",
"bairro": "Jardim Europa",
"link": "http://vejasp.abril.com.br/estabelecimento/tian",
"top3": "não",
"imagem": "tian-restaurante"
},
{
"item": "Esquina Mocotó",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "até R$ 70,00",
"preco": "até R$ 70,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Esquina Mocotó",
"endereco": "Avenida Nossa Senhora do Loreto, 1108",
"telefone": "(11) 2949 7049",
"bairro": "Vila Medeiros",
"link": "http://vejasp.abril.com.br/estabelecimento/esquina-mocoto",
"top3": "sim",
"imagem": "esquina-mocoto"
},
{
"item": "Jiquitaia",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "até R$ 70,00",
"preco": "até R$ 70,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Jiquitaia",
"endereco": "Rua Antônio Carlos, 268",
"telefone": "(11) 3262 2366",
"bairro": "Consolação",
"link": "http://vejasp.abril.com.br/estabelecimento/jiquitaia",
"top3": "não",
"imagem": "jiquitaia"
},
{
"item": "Tian",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "até R$ 70,00",
"preco": "até R$ 70,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Tian",
"endereco": "Rua Jerônimo da Veiga, 36",
"telefone": "(11) 2389 9399",
"bairro": "Jardim Europa",
"link": "http://vejasp.abril.com.br/estabelecimento/tian",
"top3": "não",
"imagem": "tian-restaurante"
},
{
"item": "Jiquitaia",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "até R$ 70,00",
"preco": "até R$ 70,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Jiquitaia",
"endereco": "Rua Antônio Carlos, 268",
"telefone": "(11) 3262 2366",
"bairro": "Consolação",
"link": "http://vejasp.abril.com.br/estabelecimento/jiquitaia",
"top3": "não",
"imagem": "jiquitaia"
},
{
"item": "Esquina Mocotó",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "até R$ 70,00",
"preco": "até R$ 70,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Esquina Mocotó",
"endereco": "Avenida Nossa Senhora do Loreto, 1108",
"telefone": "(11) 2949 7049",
"bairro": "Vila Medeiros",
"link": "http://vejasp.abril.com.br/estabelecimento/esquina-mocoto",
"top3": "sim",
"imagem": "esquina-mocoto"
},
{
"item": "Aya Japanese Cuisine",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Aya Japanese Cuisine",
"endereco": "Avenida Pedroso de Morais, 141",
"telefone": "(11) 3097 9856",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/aya-japanese-cuisine",
"top3": "sim",
"imagem": "aya-restaurante"
},
{
"item": "Naga",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Naga",
"endereco": "Rua Bandeira Paulista, 385",
"telefone": "(11) 3167 6049",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/naga",
"top3": "sim",
"imagem": "naga-restaurante"
},
{
"item": "Huto",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Huto",
"endereco": "Avenida Jandira, 677",
"telefone": "(11) 5052 6804",
"bairro": "Indianópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/huto",
"top3": "não",
"imagem": "huto-restaurante"
},
{
"item": "Brasil a Gosto",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Brasil a Gosto",
"endereco": "Rua Professor Azevedo Amaral, 70",
"telefone": "(11) 3086 3565",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/brasil-gosto#6",
"top3": "sim",
"imagem": "brasil-a-gosto"
},
{
"item": "Dalva e Dito",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Dalva e Dito",
"endereco": "Rua Padre João Manuel, 1115",
"telefone": "(11) 3068 4444",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/dalva-dito",
"top3": "sim",
"imagem": "dalva-dito"
},
{
"item": "Tordesilhas",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Tordesilhas",
"endereco": "Alameda Tietê, 489",
"telefone": "(11) 3107 7444",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/tordesilhas",
"top3": "não",
"imagem": "tordesilhas"
},
{
"item": "Vila das Meninas",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Vila das Meninas",
"endereco": "Rua Padre Carvalho, 139",
"telefone": "(11) 3037 7773",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/vila-das-meninas",
"top3": "não",
"imagem": "vila-meninas"
},
{
"item": "Capim Santo",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Capim Santo",
"endereco": "Alameda Ministro Rocha Azevedo, 471",
"telefone": "(11) 3068 8486",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/capim-santo",
"top3": "não",
"imagem": "capim-santo"
},
{
"item": "Ici Bistrô",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Ici Bistrô",
"endereco": "Rua Pará, 36",
"telefone": "(11) 3257 4064",
"bairro": "Higienópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/ici-bistro",
"top3": "sim",
"imagem": "ici-bristro"
},
{
"item": "La Casserole",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "La Casserole",
"endereco": "Largo Do Arouche, 346",
"telefone": "(11) 3331 6283",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/la-casserole",
"top3": "sim",
"imagem": "la-casserole"
},
{
"item": "Allez, Allez!",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Allez, Allez!",
"endereco": "Rua Wisard, 288",
"telefone": "(11) 3032 3325",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/allez-allez",
"top3": "sim",
"imagem": "allez-allez"
},
{
"item": "La Madonnina Ravioli",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "La Madonnina Ravioli",
"endereco": "Avenida Hélio Pelegrino, 204",
"telefone": "(11) 3842 0012",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/la-madonnina-ravioli",
"top3": "não",
"imagem": "la-madonnina"
},
{
"item": "Vicolo Nostro",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Vicolo Nostro",
"endereco": "Rua Jataituba, 29",
"telefone": "(11) 5561 5287",
"bairro": "Jardim das Acácias",
"link": "http://vejasp.abril.com.br/estabelecimento/vicolo-nostro",
"top3": "não",
"imagem": "vicolo-nostro"
},
{
"item": "Vinheria Percussi",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Vinheria Percussi",
"endereco": "Rua Cônego Eugênio Leite, 523",
"telefone": "(11) 3088 4920",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/vinheria-percussi",
"top3": "não",
"imagem": "vinheria-percussi"
},
{
"item": "Aya Japanese Cuisine",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Aya Japanese Cuisine",
"endereco": "Avenida Pedroso de Morais, 141",
"telefone": "(11) 3097 9856",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/aya-japanese-cuisine",
"top3": "sim",
"imagem": "aya-restaurante"
},
{
"item": "Naga",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Naga",
"endereco": "Rua Bandeira Paulista, 385",
"telefone": "(11) 3167 6049",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/naga",
"top3": "sim",
"imagem": "naga-restaurante"
},
{
"item": "Huto",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Huto",
"endereco": "Avenida Jandira, 677",
"telefone": "(11) 5052 6804",
"bairro": "Indianópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/huto",
"top3": "não",
"imagem": "huto-restaurante"
},
{
"item": "Brasil a Gosto",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Brasil a Gosto",
"endereco": "Rua Professor Azevedo Amaral, 71",
"telefone": "(11) 3086 3566",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/brasil-gosto#6",
"top3": "sim",
"imagem": "brasil-a-gosto"
},
{
"item": "Dalva e Dito",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Dalva e Dito",
"endereco": "Rua Padre João Manuel, 1115",
"telefone": "(11) 3068 4444",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/dalva-dito",
"top3": "sim",
"imagem": "dalva-dito"
},
{
"item": "Tordesilhas",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Tordesilhas",
"endereco": "Alameda Tietê, 489",
"telefone": "(11) 3107 7444",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/tordesilhas",
"top3": "não",
"imagem": "tordesilhas"
},
{
"item": "Vila das Meninas",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Vila das Meninas",
"endereco": "Rua Padre Carvalho, 139",
"telefone": "(11) 3037 7773",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/vila-das-meninas",
"top3": "não",
"imagem": "vila-meninas"
},
{
"item": "Capim Santo",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Capim Santo",
"endereco": "Alameda Ministro Rocha Azevedo, 471",
"telefone": "(11) 3068 8486",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/capim-santo",
"top3": "não",
"imagem": "capim-santo"
},
{
"item": "Ici Bistrô",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Ici Bistrô",
"endereco": "Rua Pará, 36",
"telefone": "(11) 3257 4064",
"bairro": "Higienópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/ici-bistro",
"top3": "sim",
"imagem": "ici-bristro"
},
{
"item": "La Casserole",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "La Casserole",
"endereco": "Largo Do Arouche, 346",
"telefone": "(11) 3331 6283",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/la-casserole",
"top3": "sim",
"imagem": "la-casserole"
},
{
"item": "Allez, Allez!",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Allez, Allez!",
"endereco": "Rua Wisard, 288",
"telefone": "(11) 3032 3325",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/allez-allez",
"top3": "sim",
"imagem": "allez-allez"
},
{
"item": "La Madonnina Ravioli",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "La Madonnina Ravioli",
"endereco": "Avenida Hélio Pelegrino, 204",
"telefone": "(11) 3842 0012",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/la-madonnina-ravioli",
"top3": "não",
"imagem": "la-madonnina"
},
{
"item": "Vicolo Nostro",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Vicolo Nostro",
"endereco": "Rua Jataituba, 29",
"telefone": "(11) 5561 5287",
"bairro": "Jardim das Acácias",
"link": "http://vejasp.abril.com.br/estabelecimento/vicolo-nostro",
"top3": "não",
"imagem": "vicolo-nostro"
},
{
"item": "Vinheria Percussi",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Vinheria Percussi",
"endereco": "Rua Cônego Eugênio Leite, 523",
"telefone": "(11) 3088 4920",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/vinheria-percussi",
"top3": "não",
"imagem": "vinheria-percussi"
},
{
"item": "Adventure Motel",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "de R$ 109,00 a R$ 186,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Adventure Motel",
"endereco": "Rua Joaquim Marra, 548",
"telefone": "(11) 2651 2222",
"bairro": "Vila Matilde",
"link": "http://vejasp.abril.com.br/estabelecimento/adventure-motel",
"top3": "não",
"imagem": "adventure-motel"
},
{
"item": "Adventure Motel",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "de R$ 109,00 a R$ 186,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Adventure Motel",
"endereco": "Rua Joaquim Marra, 548",
"telefone": "(11) 2651 2222",
"bairro": "Vila Matilde",
"link": "http://vejasp.abril.com.br/estabelecimento/adventure-motel",
"top3": "não",
"imagem": "adventure-motel"
},
{
"item": "Green Sunset",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 14,00 a R$ 30,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Museu da Imagem e do Som - MIS",
"endereco": "Avenida Europa, 158",
"telefone": "(11) 2117 4777",
"bairro": "Jardim Europa",
"link": "http://vejasp.abril.com.br/estabelecimento/museu-da-imagem-do-som",
"top3": "não",
"imagem": "green-sunset"
},
{
"item": "Green Sunset",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 14,00 a R$ 30,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Museu da Imagem e do Som - MIS",
"endereco": "Avenida Europa, 158",
"telefone": "(11) 2117 4777",
"bairro": "Jardim Europa",
"link": "http://vejasp.abril.com.br/estabelecimento/museu-da-imagem-do-som",
"top3": "não",
"imagem": "green-sunset"
},
{
"item": "X Men - Dias de um Futuro Esquecido",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "de R$ 15,00 a R$ 59,00",
"preco": "até R$ 100,00",
"tipo": "Filme",
"descricao": "-",
"estabelecimento": "-",
"endereco": "-",
"telefone": "-",
"bairro": "-",
"link": "http://vejasp.abril.com.br/atracao/x-men-dias-de-um-futuro-esquecido",
"top3": "não",
"imagem": "xmen"
},
{
"item": "Godzilla",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "de R$ 15,00 a R$ 59,00",
"preco": "até R$ 100,00",
"tipo": "Filme",
"descricao": "-",
"estabelecimento": "-",
"endereco": "-",
"telefone": "-",
"bairro": "-",
"link": "http://vejasp.abril.com.br/atracao/godzilla",
"top3": "não",
"imagem": "godzilla"
},
{
"item": "X Men - Dias de um Futuro Esquecido",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "de R$ 15,00 a R$ 59,00",
"preco": "até R$ 100,00",
"tipo": "Filme",
"descricao": "-",
"estabelecimento": "-",
"endereco": "-",
"telefone": "-",
"bairro": "-",
"link": "http://vejasp.abril.com.br/atracao/x-men-dias-de-um-futuro-esquecido",
"top3": "não",
"imagem": "xmen"
},
{
"item": "Godzilla",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "de R$ 15,00 a R$ 59,00",
"preco": "até R$ 100,00",
"tipo": "Filme",
"descricao": "-",
"estabelecimento": "-",
"endereco": "-",
"telefone": "-",
"bairro": "-",
"link": "http://vejasp.abril.com.br/atracao/godzilla",
"top3": "não",
"imagem": "godzilla"
},
{
"item": "Motel Lush by Côncavo e Convexo",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "de R$ 210,00 a R$ 260,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Motel Lush by Côncavo e Convexo",
"endereco": "Avenida do Estado, 6600",
"telefone": "(11) 2274 7433",
"bairro": "Cambuci",
"link": "http://vejasp.abril.com.br/estabelecimento/lush-by-concavo-e-convexo",
"top3": "sim",
"imagem": "motel-lush"
},
{
"item": "Motel Lush by Côncavo e Convexo",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "de R$ 210,00 a R$ 260,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Motel Lush by Côncavo e Convexo",
"endereco": "Avenida do Estado, 6600",
"telefone": "(11) 2274 7433",
"bairro": "Cambuci",
"link": "http://vejasp.abril.com.br/estabelecimento/lush-by-concavo-e-convexo",
"top3": "sim",
"imagem": "motel-lush"
},
{
"item": "Pinacoteca do Estado",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "de R$ 3,00 a R$ 6,00",
"preco": "até R$ 100,00",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Pinacoteca do Estado",
"endereco": "Praça Da Luz, 2",
"telefone": "(11) 3324 1000",
"bairro": "Bom Retiro",
"link": "http://vejasp.abril.com.br/estabelecimento/pinacoteca#2",
"top3": "sim",
"imagem": "pinaciteca"
},
{
"item": "Pinacoteca do Estado",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "de R$ 3,00 a R$ 6,00",
"preco": "até R$ 100,00",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Pinacoteca do Estado",
"endereco": "Praça Da Luz, 2",
"telefone": "(11) 3324 1000",
"bairro": "Bom Retiro",
"link": "http://vejasp.abril.com.br/estabelecimento/pinacoteca#2",
"top3": "sim",
"imagem": "pinaciteca"
},
{
"item": "Elis, A Musical",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 40,00 a R$ 140,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Teatro Alfa",
"endereco": "Rua Bento Branco De Andrade Filho, 722",
"telefone": "(11) 5693 4000",
"bairro": "Santo Amaro",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-alfa",
"top3": "sim",
"imagem": "elis-musical"
},
{
"item": "Elis, A Musical",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 40,00 a R$ 140,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Teatro Alfa",
"endereco": "Rua Bento Branco De Andrade Filho, 722",
"telefone": "(11) 5693 4000",
"bairro": "Santo Amaro",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-alfa",
"top3": "sim",
"imagem": "elis-musical"
},
{
"item": "Ney Matogrosso",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 40,00 a R$ 280,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "HSBC Brasil",
"endereco": "Rua Bragança Paulista, 1281",
"telefone": "(11) 4003 1212",
"bairro": "Vila Cruzeiro",
"link": "http://vejasp.abril.com.br/estabelecimento/hsbc-brasil",
"top3": "não",
"imagem": "ney-matogrosso"
},
{
"item": "Ney Matogrosso",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 40,00 a R$ 280,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "HSBC Brasil",
"endereco": "Rua Bragança Paulista, 1281",
"telefone": "(11) 4003 1212",
"bairro": "Vila Cruzeiro",
"link": "http://vejasp.abril.com.br/estabelecimento/hsbc-brasil",
"top3": "não",
"imagem": "ney-matogrosso"
},
{
"item": "O que o Mordomo Viu",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "de R$ 50,00 a R$ 150,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Teatro Procópio Ferreira",
"endereco": "Rua Augusta, 2823",
"telefone": "(11) 3083 4475",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-procopio-ferreira",
"top3": "não",
"imagem": "mordomo-viu"
},
{
"item": "O que o Mordomo Viu",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "de R$ 50,00 a R$ 150,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Teatro Procópio Ferreira",
"endereco": "Rua Augusta, 2823",
"telefone": "(11) 3083 4475",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-procopio-ferreira",
"top3": "não",
"imagem": "mordomo-viu"
},
{
"item": "Rita Lee Mora ao lado",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 60,00 a R$ 100,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Teatro das Artes",
"endereco": "Avenida Rebouças, 3970 - Shopping Eldorado",
"telefone": "(11) 3034 0075",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-das-artes",
"top3": "não",
"imagem": "rita-lee"
},
{
"item": "Rita Lee Mora ao lado",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 60,00 a R$ 100,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Teatro das Artes",
"endereco": "Avenida Rebouças, 3970 - Shopping Eldorado",
"telefone": "(11) 3034 0075",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-das-artes",
"top3": "não",
"imagem": "rita-lee"
},
{
"item": "Meu Deus!",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "de R$ 60,00 a R$ 80,00",
"preco": "até R$ 100,00",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Teatro Faap",
"endereco": "Rua Alagoas, 903",
"telefone": "(11) 3662 7233",
"bairro": "Higienópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-faap",
"top3": "não",
"imagem": "meu-deus"
},
{
"item": "Meu Deus!",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "de R$ 60,00 a R$ 80,00",
"preco": "até R$ 100,00",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Teatro Faap",
"endereco": "Rua Alagoas, 903",
"telefone": "(11) 3662 7233",
"bairro": "Higienópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-faap",
"top3": "não",
"imagem": "meu-deus"
},
{
"item": "Djavan",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 70,00 a R$ 240,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Citibank Hall",
"endereco": "Avenida das Nações Unidas, 17955",
"telefone": "(11) 4003 5588",
"bairro": "Vila Almeida",
"link": "http://vejasp.abril.com.br/estabelecimento/citibank-hall",
"top3": "sim",
"imagem": "djavan"
},
{
"item": "Djavan",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 70,00 a R$ 240,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Citibank Hall",
"endereco": "Avenida das Nações Unidas, 17955",
"telefone": "(11) 4003 5588",
"bairro": "Vila Almeida",
"link": "http://vejasp.abril.com.br/estabelecimento/citibank-hall",
"top3": "sim",
"imagem": "djavan"
},
{
"item": "Fisherman's Table",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Fisherman's Table",
"endereco": "Rua Pedroso Alvarenga, 554",
"telefone": "(11) 3167 3605",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/fishermans-table",
"top3": "não",
"imagem": "fisherman"
},
{
"item": "Tantra",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Tantra",
"endereco": "Rua Chilon, 364",
"telefone": "(11) 3846 7112",
"bairro": "Vila Olímpia",
"link": "http://vejasp.abril.com.br/estabelecimento/tantra",
"top3": "não",
"imagem": "tantra-restaurante"
},
{
"item": "Colher de Pau",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Colher de Pau",
"endereco": "Rua Doutor Mário Ferraz, 563",
"telefone": "(11) 3079 3087",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/colher-de-pau",
"top3": "não",
"imagem": "colher-pau"
},
{
"item": "Consulado da Bahia",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Consulado da Bahia",
"endereco": "Rua dos Pinheiros, 534",
"telefone": "(11) 3085 3873",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/consulado-da-bahia",
"top3": "não",
"imagem": "consulado-bahia"
},
{
"item": "L'Amitié",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "L'Amitié",
"endereco": "Rua Manuel Guedes, 233",
"telefone": "(11) 3078 5919",
"bairro": "Jardim Europa",
"link": "http://vejasp.abril.com.br/estabelecimento/l-amitie",
"top3": "não",
"imagem": "lamitie"
},
{
"item": "La Tartine",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "La Tartine",
"endereco": "Rua Fernando de Albuquerque, 267",
"telefone": "(11) 3259 2090",
"bairro": "Consolação",
"link": "http://vejasp.abril.com.br/estabelecimento/la-tartine",
"top3": "não",
"imagem": "la-tartine"
},
{
"item": "Robin des Bois",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Robin des Bois",
"endereco": "Rua Capote Valente, 86",
"telefone": "(11) 3063 2795",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/robin-des-bois",
"top3": "não",
"imagem": "robin-bois"
},
{
"item": "Sarrasin",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Sarrasin",
"endereco": "Rua Costa Carvalho, 182",
"telefone": "(11) 3031 1594",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/sarrasin",
"top3": "não",
"imagem": "sarrasin"
},
{
"item": "Divina Itália",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Divina Itália",
"endereco": "Rua Mourato Coelho, 789",
"telefone": "(11) 3814 3344",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/divina-italia",
"top3": "não",
"imagem": "divina-italia"
},
{
"item": "Trappo Trattoria",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Trappo Trattoria",
"endereco": "Rua da Consolação, 2967",
"telefone": "(11) 3063 4864",
"bairro": "Consolação",
"link": "http://vejasp.abril.com.br/estabelecimento/tappo-trattoria",
"top3": "não",
"imagem": "tappo-tratoria"
},
{
"item": "Vito",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Vito",
"endereco": "Rua Isabel De Castela, 529",
"telefone": "(11) 3032 1469",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/vito",
"top3": "sim",
"imagem": "vito"
},
{
"item": "Pasta D'Autori Cucina Originale",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Pasta D'Autori Cucina Originale",
"endereco": "Rua Professor Atílio Innocenti, 743",
"telefone": "(11) 3044 0615",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/pasta-d-autori-cucina-originale",
"top3": "não",
"imagem": "pasta-dautori"
},
{
"item": "Fisherman's Table",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Fisherman's Table",
"endereco": "Rua Pedroso Alvarenga, 554",
"telefone": "(11) 3167 3605",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/fishermans-table",
"top3": "não",
"imagem": "fisherman"
},
{
"item": "Tantra",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Tantra",
"endereco": "Rua Chilon, 364",
"telefone": "(11) 3846 7112",
"bairro": "Vila Olímpia",
"link": "http://vejasp.abril.com.br/estabelecimento/tantra",
"top3": "não",
"imagem": "tantra-restaurante"
},
{
"item": "Colher de Pau",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Colher de Pau",
"endereco": "Rua Doutor Mário Ferraz, 563",
"telefone": "(11) 3079 3087",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/colher-de-pau",
"top3": "não",
"imagem": "colher-pau"
},
{
"item": "Consulado da Bahia",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Consulado da Bahia",
"endereco": "Rua dos Pinheiros, 534",
"telefone": "(11) 3085 3873",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/consulado-da-bahia",
"top3": "não",
"imagem": "consulado-bahia"
},
{
"item": "L'Amitié",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "L'Amitié",
"endereco": "Rua Manuel Guedes, 233",
"telefone": "(11) 3078 5919",
"bairro": "Jardim Europa",
"link": "http://vejasp.abril.com.br/estabelecimento/l-amitie",
"top3": "não",
"imagem": "lamitie"
},
{
"item": "La Tartine",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "La Tartine",
"endereco": "Rua Fernando de Albuquerque, 267",
"telefone": "(11) 3259 2090",
"bairro": "Consolação",
"link": "http://vejasp.abril.com.br/estabelecimento/la-tartine",
"top3": "não",
"imagem": "la-tartine"
},
{
"item": "Robin des Bois",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Robin des Bois",
"endereco": "Rua Capote Valente, 86",
"telefone": "(11) 3063 2795",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/robin-des-bois",
"top3": "não",
"imagem": "robin-bois"
},
{
"item": "Sarrasin",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Sarrasin",
"endereco": "Rua Costa Carvalho, 182",
"telefone": "(11) 3031 1594",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/sarrasin",
"top3": "não",
"imagem": "sarrasin"
},
{
"item": "Divina Itália",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Divina Itália",
"endereco": "Rua Mourato Coelho, 789",
"telefone": "(11) 3814 3344",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/divina-italia",
"top3": "não",
"imagem": "divina-italia"
},
{
"item": "Trappo Trattoria",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Trappo Trattoria",
"endereco": "Rua da Consolação, 2967",
"telefone": "(11) 3063 4864",
"bairro": "Consolação",
"link": "http://vejasp.abril.com.br/estabelecimento/tappo-trattoria",
"top3": "não",
"imagem": "tappo-tratoria"
},
{
"item": "Vito",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Vito",
"endereco": "Rua Isabel De Castela, 529",
"telefone": "(11) 3032 1469",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/vito",
"top3": "sim",
"imagem": "vito"
},
{
"item": "Pasta D'Autori Cucina Originale",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Pasta D'Autori Cucina Originale",
"endereco": "Rua Professor Atílio Innocenti, 743",
"telefone": "(11) 3044 0616",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/pasta-d-autori-cucina-originale",
"top3": "não",
"imagem": "pasta-dautori"
},
{
"item": "All of Jazz",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "All of Jazz",
"endereco": "Rua João Cachoeira, 1366",
"telefone": "(11) 3849 1345",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/all-of-jazz",
"top3": "não",
"imagem": "all-of-jazz"
},
{
"item": "All of Jazz",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "All of Jazz",
"endereco": "Rua João Cachoeira, 1366",
"telefone": "(11) 3849 1345",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/all-of-jazz",
"top3": "não",
"imagem": "all-of-jazz"
},
{
"item": "Passeio pelo Teatro Municipal",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Teatro Municipal",
"endereco": "Praça Ramos De Azevedo, s/nº -",
"telefone": "(11) 3397 0327",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-municipal",
"top3": "sim",
"imagem": "teatro-municipal"
},
{
"item": "Feira da Praça Benedito Calixto",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Praça Benedito Calixto",
"endereco": "Praça Benedito Calixto, 158/162",
"telefone": "(11) 3081 0641",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/feira-praca-benedito-calixto",
"top3": "sim",
"imagem": "benedito-calixo"
},
{
"item": "Yayoi Kusama",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Instituto Tomie Ohtake",
"endereco": "Rua Dos Coropés, 88",
"telefone": "(11) 2245 1900",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/instituto-tomie-ohtake-pinheiros",
"top3": "sim",
"imagem": "yayoi-kusama"
},
{
"item": "Centro da Memória do Circo",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Galeria Olido",
"endereco": "Avenida São João, 473",
"telefone": "(11) 3397 0171",
"bairro": "Centro",
"link": "http://vejasp.abril.com.br/estabelecimento/galeria-olido",
"top3": "não",
"imagem": "centro-memoria"
},
{
"item": "Jardim Botânico",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Jardim Botânico",
"endereco": "Avenida Miguel Estéfno, 3031",
"telefone": "(11) 5067 6049",
"bairro": "Saúde",
"link": "http://vejasp.abril.com.br/estabelecimento/jardim-botanico",
"top3": "sim",
"imagem": "jardim-botanico"
},
{
"item": "Parque Villa-Lobos",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Parque Villa-Lobos",
"endereco": "Avenida Professor Fonseca Rodrigues, 2001",
"telefone": "(11) 3023 0316",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/parque-villa-lobos",
"top3": "não",
"imagem": "villa-lobos"
},
{
"item": "Parque do Ibirapuera",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Parque do Ibirapuera",
"endereco": "Avenida Pedro Álvares Cabral, s/n",
"telefone": "(11) 5573 4180",
"bairro": "Parque Ibirapuera",
"link": "http://vejasp.abril.com.br/estabelecimento/parque-do-ibirapuera",
"top3": "não",
"imagem": "ibirapuera"
},
{
"item": "Jardim Parque da Independência",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Parque da Independência",
"endereco": "Avenida Nazaré, s/n",
"telefone": "(11) 2273 7250",
"bairro": "Ipiranga",
"link": "http://vejasp.abril.com.br/estabelecimento/parque-da-independencia#2",
"top3": "não",
"imagem": "parque-independencia"
},
{
"item": "Praça do Por do Sol",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Praça Coronel Custódio Fernandes Pinheiros",
"endereco": "Rua Desembargador Ferreira França, S/N",
"telefone": "-",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/praca-cel-custodio-fernandes-pinheiros-por-do-sol",
"top3": "sim",
"imagem": "praca-por-sol"
},
{
"item": "Praça Victor Civita",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Praça Victor Civita",
"endereco": "Rua Sumidouro, 580",
"telefone": "-",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/praca-victor-civita",
"top3": "não",
"imagem": "vitor-civita"
},
{
"item": "Pico do Jaraguá",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Pico do Jaraguá",
"endereco": "Rua Antônio Cardoso Nogueira, 539",
"telefone": "(11) 3941 2162",
"bairro": "Vila Chica Luisa",
"link": "http://vejasp.abril.com.br/estabelecimento/pico-do-jaragua",
"top3": "não",
"imagem": "pico-jaragua"
},
{
"item": "Galeria do Rock",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Galeria do Rock",
"endereco": "Rua Vinte E Quatro De Maio, 62",
"telefone": "-",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/galeria-do-rock",
"top3": "não",
"imagem": "galeria-rock"
},
{
"item": "Música de Chuteiras",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Sesc Pompéia",
"endereco": "Rua Clélia, 93",
"telefone": "(11) 3871 7700",
"bairro": "Água Branca",
"link": "http://vejasp.abril.com.br/estabelecimento/sesc-pompeia",
"top3": "não",
"imagem": "musica-chuteira"
},
{
"item": "Ciclofaixa Guarapiranga",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Cliclofaixa Guarapiranga",
"endereco": "-",
"telefone": "-",
"bairro": "-",
"link": "http://vejasp.abril.com.br/atracao/ciclofaixa-guarapiranga",
"top3": "não",
"imagem": "ciclofaixa"
},
{
"item": "Passeio pelo Teatro Municipal",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Teatro Municipal",
"endereco": "Praça Ramos De Azevedo, s/nº -",
"telefone": "(11) 3397 0327",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-municipal",
"top3": "sim",
"imagem": "teatro-municipal"
},
{
"item": "Feira da Praça Benedito Calixto",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Praça Benedito Calixto",
"endereco": "Praça Benedito Calixto, 158/162",
"telefone": "(11) 3081 0641",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/feira-praca-benedito-calixto",
"top3": "sim",
"imagem": "benedito-calixo"
},
{
"item": "Yayoi Kusama",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Instituto Tomie Ohtake",
"endereco": "Rua Dos Coropés, 88",
"telefone": "(11) 2245 1900",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/instituto-tomie-ohtake-pinheiros",
"top3": "sim",
"imagem": "yayoi-kusama"
},
{
"item": "Centro da Memória do Circo",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Galeria Olido",
"endereco": "Avenida São João, 473",
"telefone": "(11) 3397 0171",
"bairro": "Centro",
"link": "http://vejasp.abril.com.br/estabelecimento/galeria-olido",
"top3": "não",
"imagem": "centro-memoria"
},
{
"item": "Jardim Botânico",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Jardim Botânico",
"endereco": "Avenida Miguel Estéfno, 3031",
"telefone": "(11) 5067 6049",
"bairro": "Saúde",
"link": "http://vejasp.abril.com.br/estabelecimento/jardim-botanico",
"top3": "sim",
"imagem": "jardim-botanico"
},
{
"item": "Parque Villa-Lobos",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Parque Villa-Lobos",
"endereco": "Avenida Professor Fonseca Rodrigues, 2001",
"telefone": "(11) 3023 0316",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/parque-villa-lobos",
"top3": "não",
"imagem": "villa-lobos"
},
{
"item": "Parque do Ibirapuera",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Parque do Ibirapuera",
"endereco": "Avenida Pedro Álvares Cabral, s/n",
"telefone": "(11) 5573 4180",
"bairro": "Parque Ibirapuera",
"link": "http://vejasp.abril.com.br/estabelecimento/parque-do-ibirapuera",
"top3": "não",
"imagem": "ibirapuera"
},
{
"item": "Jardim Parque da Independência",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Parque da Independência",
"endereco": "Avenida Nazaré, s/n",
"telefone": "(11) 2273 7250",
"bairro": "Ipiranga",
"link": "http://vejasp.abril.com.br/estabelecimento/parque-da-independencia#2",
"top3": "não",
"imagem": "parque-independencia"
},
{
"item": "Praça do Por do Sol",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Praça Coronel Custódio Fernandes Pinheiros",
"endereco": "Rua Desembargador Ferreira França, S/N",
"telefone": "-",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/praca-cel-custodio-fernandes-pinheiros-por-do-sol",
"top3": "sim",
"imagem": "praca-por-sol"
},
{
"item": "Praça Victor Civita",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Praça Victor Civita",
"endereco": "Rua Sumidouro, 580",
"telefone": "-",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/praca-victor-civita",
"top3": "não",
"imagem": "vitor-civita"
},
{
"item": "Pico do Jaraguá",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Pico do Jaraguá",
"endereco": "Rua Antônio Cardoso Nogueira, 539",
"telefone": "(11) 3941 2162",
"bairro": "Vila Chica Luisa",
"link": "http://vejasp.abril.com.br/estabelecimento/pico-do-jaragua",
"top3": "não",
"imagem": "pico-jaragua"
},
{
"item": "Galeria do Rock",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Galeria do Rock",
"endereco": "Rua Vinte E Quatro De Maio, 62",
"telefone": "",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/galeria-do-rock",
"top3": "não",
"imagem": "galeria-rock"
},
{
"item": "Música de Chuteiras",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Sesc Pompéia",
"endereco": "Rua Clélia, 93",
"telefone": "(11) 3871 7700",
"bairro": "Água Branca",
"link": "http://vejasp.abril.com.br/estabelecimento/sesc-pompeia",
"top3": "não",
"imagem": "musica-chuteira"
},
{
"item": "Ciclofaixa Guarapiranga",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Cliclofaixa Guarapiranga",
"endereco": "-",
"telefone": "-",
"bairro": "-",
"link": "http://vejasp.abril.com.br/atracao/ciclofaixa-guarapiranga",
"top3": "não",
"imagem": "ciclofaixa"
},
{
"item": "Legging",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 106,00",
"preco": "até R$ 100,00",
"tipo": "Vestuário",
"descricao": "Legging snake",
"estabelecimento": "Lupo - Jardins",
"endereco": "Alameda Lorena, 1647",
"telefone": "(11) 3081 4833",
"bairro": "Jardim Paulista ",
"link": "http://vejasp.abril.com.br/estabelecimento/lupo-jardins",
"top3": "não",
"imagem": "esportistaF9"
},
{
"item": "Samba-canção",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 112,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Samba-canção xadrez",
"estabelecimento": "New Captain",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://shop.newcaptain.com.br/",
"top3": "não",
"imagem": "hipsterM7"
},
{
"item": "Perfume",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 119,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Beleza",
"descricao": "Perfume L'Eau par Kenzo 50ml",
"estabelecimento": "Sephora - Shopping JK Iguatemi",
"endereco": "Avenida Presidente Juscelino Kubitschek, 2041",
"telefone": "(11) 3152 6692",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/sephora-shopping-jk-iguatemi",
"top3": "não",
"imagem": "basicoF1"
},
{
"item": "Bermuda",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 119,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Bermuda para atividade física",
"estabelecimento": "New Balance - Shopping Morumbi",
"endereco": "Avenida Roque Petroni Júnior, 1089",
"telefone": "(11) 5181 6136",
"bairro": "Jardim das Acácias",
"link": "http://vejasp.abril.com.br/estabelecimento/new-balance",
"top3": "não",
"imagem": "esportistaM2"
},
{
"item": "Camiseta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 128,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Camiseta de algodão",
"estabelecimento": "Noir Le Lis - Shopping Anália Franco",
"endereco": "Avenida Regente Feijó, 1739",
"telefone": "(11) 2643 4550",
"bairro": "Vila Regente Feijó",
"link": "http://vejasp.abril.com.br/estabelecimento/le-lis-blanc-shopping-analia-franco",
"top3": "não",
"imagem": "sofisticadoM7"
},
{
"item": "Bermuda",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 129,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Bermuda jeans",
"estabelecimento": "Levi's - Oscar Freire",
"endereco": "Rua Oscar Freire, 1128",
"telefone": "(11) 3062 2879",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/levis-oscar-freire",
"top3": "não",
"imagem": "basicoM8"
},
{
"item": "Tênis",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 129,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Tênis com estampa de corações",
"estabelecimento": "Art Walk - Shopping Villa-Lobos",
"endereco": "Avenida das Nações Unidas, 4777",
"telefone": "(11) 3021 7329",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/artwalk-shopping-villa-lobos",
"top3": "sim",
"imagem": "hipsterF4"
},
{
"item": "Jaqueta",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 139,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Jaqueta de estampa geométrica",
"estabelecimento": "Puma",
"endereco": "E-commerce",
"telefone": "",
"bairro": "",
"link": "http://shop.brasil.puma.com/",
"top3": "não",
"imagem": "hipsterF8"
},
{
"item": "Bolsa ",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 139,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "-",
"estabelecimento": "Fila - Oscar Freire",
"endereco": "Rua Oscar Freire, 1092 - Cerqueira César",
"telefone": "(11) 3798 9054",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/fila-store",
"top3": "não",
"imagem": "hipsterF9"
},
{
"item": "Jaqueta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 139,99",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Jaqueta fitness",
"estabelecimento": "Hering - Sumarezinho",
"endereco": "Rua Harmonia, 394",
"telefone": "(11) 3032 7972",
"bairro": "Vila Madalena",
"link": "http://vejasp.abril.com.br/estabelecimento/hering-sumarezinho",
"top3": "não",
"imagem": "esportistaM8"
},
{
"item": "Calça",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 149,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Calça de veludo canelado",
"estabelecimento": "UseLets",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.uselets.com.br/",
"top3": "não",
"imagem": "basicoF7"
},
{
"item": "Coqueteleira",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 149,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Decoração",
"descricao": "Coqueteleira de alumínio",
"estabelecimento": "Imaginarium - Shopping Ibirapuera",
"endereco": "Avenida Ibirapuera, 3103",
"telefone": "(11) 5561 9777",
"bairro": "Moema",
"link": "http://vejasp.abril.com.br/estabelecimento/imaginarium-shopping-ibirapuera",
"top3": "não",
"imagem": "hipsterM3"
},
{
"item": "Sapatênis",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 159,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Calçado",
"descricao": "Sapatênis de lona",
"estabelecimento": "Timberland para World Tennis - Shopping Bourbon",
"endereco": "Rua Turiassu, 2100",
"telefone": "(11) 3675 3481",
"bairro": "Perdizes",
"link": "http://vejasp.abril.com.br/estabelecimento/world-tennis-shopping-bourbon",
"top3": "sim",
"imagem": "basicoM4"
},
{
"item": "Camisa",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 159,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Camisa de algodão listrada",
"estabelecimento": "Siberian - Shopping Bourbon",
"endereco": "Rua Turiassu, 2100",
"telefone": "(11) 3807 3521",
"bairro": "Perdizes",
"link": "http://vejasp.abril.com.br/estabelecimento/siberian-shopping-bourbon",
"top3": "não",
"imagem": "sofisticadoM5"
},
{
"item": "Nécessaire",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 168,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Nécessaire de couro",
"estabelecimento": "Trousseau - Moema",
"endereco": "Rua Escobar Ortiz, 482",
"telefone": "(11) 3044 3582",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/trousseau-moema",
"top3": "não",
"imagem": "basicoF9"
},
{
"item": "Camiseta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 169,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Camiseta com gola V",
"estabelecimento": "Ricardo Almeida - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 2232",
"telefone": "(11) 3812 6947",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/ricardo-almeida-shopping-iguatemi",
"top3": "não",
"imagem": "sofisticadoM8"
},
{
"item": "Brunch no Mosteiro de São Bento",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "R$ 170,00 por pessoa",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Mosteiro de São Bento",
"endereco": "Largo São Bento, s/n",
"telefone": "(11) 3328 8799",
"bairro": "Centro",
"link": "http://vejasp.abril.com.br/estabelecimento/mosteiro-de-sao-bento#12",
"top3": "não",
"imagem": "brunch-mosteiro"
},
{
"item": "Brunch no Mosteiro de São Bento",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "R$ 170,00 por pessoa",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Mosteiro de São Bento",
"endereco": "Largo São Bento, s/n",
"telefone": "(11) 3328 8799",
"bairro": "Centro",
"link": "http://vejasp.abril.com.br/estabelecimento/mosteiro-de-sao-bento#12",
"top3": "não",
"imagem": "brunch-mosteiro"
},
{
"item": "Brincos",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 179,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Brincos de metal dourado",
"estabelecimento": "Luiza Perea",
"endereco": "Rua Girassol, 157",
"telefone": "(11) 3032 0136",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/luiza-perea",
"top3": "não",
"imagem": "sofisticadoF2"
},
{
"item": "Gravata",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 179,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Gravata de seda listrada",
"estabelecimento": "Ricardo Almeida - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 2232",
"telefone": "(11) 3812 6947",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/ricardo-almeida-shopping-iguatemi",
"top3": "sim",
"imagem": "sofisticadoM2"
},
{
"item": "Kit para o barbear",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 183,30",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Beleza",
"descricao": "Kit com produtos para o barbear",
"estabelecimento": "Sparkkli Home Spa",
"endereco": "Rua Domingos Fernandes, 572",
"telefone": "(11) 3846 6045",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/sparkkli-home-spa",
"top3": "não",
"imagem": "sofisticadoM9"
},
{
"item": "Legging",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 188,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Legging estampada",
"estabelecimento": "Cia. Marítima - Shopping Morumbi",
"endereco": "Avenida Roque Petroni Júnior, 1089",
"telefone": "(11) 5181 2297",
"bairro": "Jardim das Acácias",
"link": "http://vejasp.abril.com.br/estabelecimento/ciamaritima-shopping-morumbi",
"top3": "não",
"imagem": "esportistaF5"
},
{
"item": "Jaqueta",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 189,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Jaqueta em matelassê",
"estabelecimento": "Lojão do Brás",
"endereco": "Largo da Concórdia, 88",
"telefone": "(11) 2696 5133",
"bairro": "Brás",
"link": "http://vejasp.abril.com.br/estabelecimento/lojao-do-bras-bras-1",
"top3": "não",
"imagem": "basicoF6"
},
{
"item": "Chapéu",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 189,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Chapéu vermelho com laço",
"estabelecimento": "Accessorize - Jardins",
"endereco": "Rua Haddock Lobo, 1491 - Cerqueira César",
"telefone": "(11) 3061 5136",
"bairro": "Jardins",
"link": "http://vejasp.abril.com.br/estabelecimento/accessorize-jardins",
"top3": "sim",
"imagem": "hipsterF1"
},
{
"item": "Moletom",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 189,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Tricô de lurex",
"estabelecimento": "Gap - Shopping JK Iguatemi",
"endereco": "Avenida Presidente Juscelino Kubitschek, 2041",
"telefone": "(11) 3038 2527",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/gap-shopping-jk-iguatemi",
"top3": "não",
"imagem": "sofisticadoF7"
},
{
"item": "Óculos",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 195,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Óculos em acetato",
"estabelecimento": "Ótica Ventura - Jardins",
"endereco": "Rua Bela Cintra, 1845",
"telefone": "(11) 3083 7090",
"bairro": "Consolação",
"link": "http://vejasp.abril.com.br/estabelecimento/otica-ventura",
"top3": "não",
"imagem": "hipsterM2"
},
{
"item": "Top",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 198,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Cropped top",
"estabelecimento": "John John - Oscar Freire",
"endereco": "Rua Oscar Freire, 798",
"telefone": "(11) 3061 9906",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/john-john-denim",
"top3": "sim",
"imagem": "esportistaF3"
},
{
"item": "Calça",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 199,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Calça de sarja colorida",
"estabelecimento": "Crawford - Shopping Morumbi",
"endereco": "Avenida Roque Petroni Júnior, 1089",
"telefone": "(11) 5189 4609",
"bairro": "Jardim das Acácias",
"link": "http://vejasp.abril.com.br/estabelecimento/crawford-shopping-morumbi",
"top3": "sim",
"imagem": "sofisticadoM6"
},
{
"item": "Shorts",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 199,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Shorts de corrida Stella McCartney",
"estabelecimento": "Adidas - Shopping Eldorado",
"endereco": "Avenida Rebouças, 3970",
"telefone": "(11) 2197 7415",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/adidas-performance-shopping-eldorado",
"top3": "não",
"imagem": "esportistaF6"
},
{
"item": "Camiseta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 199,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Camiseta manga longa",
"estabelecimento": "Mr. Kitsch - Shopping Metrô Tucuruvi",
"endereco": "Avenida Doutor Antônio Maria Laet, 566",
"telefone": "(11) 4873 0810",
"bairro": "Parada Inglesa",
"link": "http://vejasp.abril.com.br/estabelecimento/mr-kitsch-shopping-metro-tucuruvi",
"top3": "não",
"imagem": "basicoM5"
},
{
"item": "Bermuda",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 211,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Bermuda esportiva",
"estabelecimento": "Star Point - Shopping Villa-Lobos",
"endereco": "Avenida Das Nações Unidas, 4777",
"telefone": "(11) 3022 2657",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/star-point-shop-villa-lobos",
"top3": "não",
"imagem": "basicoM9"
},
{
"item": "Saia",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 219,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Saia evasê estampada",
"estabelecimento": "Antix - Shopping Vila Olímpia",
"endereco": "Rua Olimpíadas, 360",
"telefone": "(11) 3047 6292",
"bairro": "Vila Olímpia",
"link": "http://vejasp.abril.com.br/estabelecimento/antix",
"top3": "não",
"imagem": "sofisticadoF3"
},
{
"item": "Blusa",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 219,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Blusa de crepe com renda",
"estabelecimento": "Costume para OQVestir",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.oqvestir.com.br/",
"top3": "não",
"imagem": "sofisticadoF6"
},
{
"item": "Abotoadoras",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 219,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Abotoadoras de metal",
"estabelecimento": "Aramis - Shopping Bourbon",
"endereco": "Rua Turiassu, 2100",
"telefone": "(11) 3892 4313",
"bairro": "Perdizes",
"link": "http://vejasp.abril.com.br/estabelecimento/aramis-shopping-bourbon",
"top3": "sim",
"imagem": "sofisticadoM1"
},
{
"item": "Passeio Noturno no Zoológico",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "R$ 22,90",
"preco": "até R$ 100,00",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Zoológico de São Paulo",
"endereco": "Avenida Miguel Estéfno, 4241",
"telefone": "(11) 5073 0811",
"bairro": "Saúde",
"link": "http://vejasp.abril.com.br/estabelecimento/zoologico-de-sao-paulo",
"top3": "não",
"imagem": "zoologico"
},
{
"item": "Passeio Noturno no Zoológico",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "R$ 22,90",
"preco": "até R$ 100,00",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Zoológico de São Paulo",
"endereco": "Avenida Miguel Estéfno, 4241",
"telefone": "(11) 5073 0811",
"bairro": "Saúde",
"link": "http://vejasp.abril.com.br/estabelecimento/zoologico-de-sao-paulo",
"top3": "não",
"imagem": "zoologico"
},
{
"item": "Jaqueta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 221,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Jaqueta esportiva",
"estabelecimento": "Lupo - Jardins",
"endereco": "Alameda Lorena, 1647",
"telefone": "(11) 3081 4833",
"bairro": "Jardim Paulista ",
"link": "http://vejasp.abril.com.br/estabelecimento/lupo-jardins",
"top3": "sim",
"imagem": "esportistaM3"
},
{
"item": "Camiseta",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 228,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Camiseta french bulldog com óculos",
"estabelecimento": "Bo.Bô - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 223",
"telefone": "(11) 3032 6171",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/bo-bo-shopping-iguatemi",
"top3": "não",
"imagem": "hipsterF6"
},
{
"item": "Camiseta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 228,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Camiseta estampada",
"estabelecimento": "Noir Le Lis - Shopping Anália Franco",
"endereco": "Avenida Regente Feijó, 1739",
"telefone": "(11) 2643 4550",
"bairro": "Jardim Anália Franco",
"link": "http://vejasp.abril.com.br/estabelecimento/le-lis-blanc-shopping-analia-franco",
"top3": "não",
"imagem": "hipsterM5"
},
{
"item": "Saia",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 229,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Saia plissada xadrez",
"estabelecimento": "Cori - Shopping Villa-Lobos",
"endereco": "Avenida Das Nações Unidas, 4777",
"telefone": "(11) 3038 2538",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/cori-shopping-villa-lobos",
"top3": "não",
"imagem": "hipsterF5"
},
{
"item": "Bermuda",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 229,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Bermuda estampada",
"estabelecimento": "Shorts Co.",
"endereco": "Rua Doutor Melo Alves, 498",
"telefone": "(11) 2387 4440",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/shorts-co",
"top3": "não",
"imagem": "esportistaM9"
},
{
"item": "Camiseta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 229,90",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Camiseta oficial da Seleção Brasileira",
"estabelecimento": "Centauro - Shopping Center Norte",
"endereco": "Travessa Casalbuono, 120",
"telefone": "(11) 2221 1771",
"bairro": "Vila Guilherme",
"link": "http://vejasp.abril.com.br/estabelecimento/centauro-shopping-center-norte",
"top3": "sim",
"imagem": "esportistaM7"
},
{
"item": "Capinha para celular",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 240,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Case para iPhone em madeira",
"estabelecimento": "Grife Pau Brasil",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.grifepaubrasil.com.br/",
"top3": "não",
"imagem": "hipsterF3"
},
{
"item": "Brincos",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 248,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Brincos com pedras preciosas",
"estabelecimento": "Raphael Falci - Shopping Cidade Jardim",
"endereco": "Av. Magalhães de Castro, 12000",
"telefone": "(11) 3198-9339",
"bairro": "Morumbi",
"link": "http://vejasp.abril.com.br/estabelecimento/raphael-falci",
"top3": "não",
"imagem": "basicoF2"
},
{
"item": "Bolsa ",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 249,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Bolsa de couro com alça longa",
"estabelecimento": "Lily's Closet",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.lillyscloset.com.br/lojaonline/",
"top3": "não",
"imagem": "hipsterF2"
},
{
"item": "Perfume",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 249,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Beleza",
"descricao": "Perfume Gentlemen Only Givenchy",
"estabelecimento": "Sephora - Shopping JK Iguatemi",
"endereco": "Avenida Presidente Juscelino Kubitschek, 2041",
"telefone": "(11) 3152 6692",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/sephora-shopping-jk-iguatemi",
"top3": "não",
"imagem": "basicoM2"
},
{
"item": "Sandália",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 250,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Calçado",
"descricao": "Sandália rasteira metalizada",
"estabelecimento": "Schutz - Shopping Ibirapuera",
"endereco": "Avenida Ibirapuera, 3103",
"telefone": "(11) 5093 8899",
"bairro": "Moema",
"link": "http://vejasp.abril.com.br/estabelecimento/schutz-shopping-ibirapuera",
"top3": "não",
"imagem": "sofisticadoF8"
},
{
"item": "Calça",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 250,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Calça de Alfaiataria",
"estabelecimento": "Richards - Shopping Villa-Lobos",
"endereco": "Avenida Das Nações Unidas, 4777",
"telefone": "(11) 3022 5691",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/richards-shopping-villa-lobos",
"top3": "não",
"imagem": "basicoM6"
},
{
"item": "Óculos",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 269,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Óculos de sol em metal",
"estabelecimento": "Chilli Beans - Oscar Freire",
"endereco": "Rua Oscar Freire, 1072",
"telefone": "(11) 3063 5575",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/chilli-beans-flagship",
"top3": "não",
"imagem": "basicoF3"
},
{
"item": "Polo",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 279,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Camiseta polo feminina",
"estabelecimento": "Lacoste - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 2232",
"telefone": "(11) 3812 4908",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/lacoste-shopping-iguatemi",
"top3": "não",
"imagem": "esportistaF7"
},
{
"item": "Blusa",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 279,90",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Blusa de cetim",
"estabelecimento": "OQVestir",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.oqvestir.com.br/",
"top3": "sim",
"imagem": "basicoF8"
},
{
"item": "Tênis",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 279,90",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Sapatênis cano alto",
"estabelecimento": "Mundial Calçados - Morumbi Shopping",
"endereco": "Avenida Roque Petroni Júnior, 1089",
"telefone": "(11) 5181 8880",
"bairro": "Jardim das Acácias",
"link": "http://vejasp.abril.com.br/estabelecimento/mundial-calcados-morumbi-shopping",
"top3": "não",
"imagem": "hipsterM4"
},
{
"item": "Cardigã",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 280,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Cardigã de tricô colorido",
"estabelecimento": "Zapalla - Shopping Cidade Jaridm",
"endereco": "Avenida Magalhães De Castro, 12000",
"telefone": "(11) 3552 3110",
"bairro": "Santo Amaro",
"link": "http://vejasp.abril.com.br/estabelecimento/zapalla-shopping-cidade-jardim",
"top3": " não",
"imagem": "sofisticadoM4"
},
{
"item": "Pijama",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 289,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Pijama de flanela",
"estabelecimento": "Any Any - Shopping Ibirapuera",
"endereco": "Avenida Ibirapuera, 3103",
"telefone": "(11) 5535 5328",
"bairro": "Moema",
"link": "http://vejasp.abril.com.br/estabelecimento/any-any-shopping-ibirapuera",
"top3": "não",
"imagem": "basicoM7"
},
{
"item": "Pulseira",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 295,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Bracelete com cristais Swarovski",
"estabelecimento": "Swarovski - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 2232",
"telefone": "(11) 3816 7111",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/swarovski-shopping-iguatemi",
"top3": "sim",
"imagem": "sofisticadoF1"
},
{
"item": "Tênis",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 299,90",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Calçado",
"descricao": "Tênis New Balance",
"estabelecimento": "New Balance - Shopping Morumbi",
"endereco": "Avenida Roque Petroni Júnior, 1089",
"telefone": "(11) 5181 6136",
"bairro": "Jardim das Acácias",
"link": "http://vejasp.abril.com.br/estabelecimento/new-balance",
"top3": "não",
"imagem": "esportistaM1"
},
{
"item": "Tênis",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 299,90",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Calçado",
"descricao": "Tênis Anatomix Fila",
"estabelecimento": "Fila Store - Oscar Freire",
"endereco": "Rua Oscar Freire, 1092",
"telefone": "(11) 3798 9054",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/fila-store",
"top3": "não",
"imagem": "esportistaM5"
},
{
"item": "Tênis",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 300,00",
"preco": "acima de R$ 300,00",
"tipo": "Calçado",
"descricao": "Tênis Faas Puma",
"estabelecimento": "Puma",
"endereco": "E-commerce",
"telefone": "",
"bairro": "",
"link": "http://shop.brasil.puma.com/",
"top3": "sim",
"imagem": "esportistaF1"
},
{
"item": "Nécessaire",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 310,00",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Nécessaire estampada",
"estabelecimento": "Tory Burch - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 2232",
"telefone": "(11) 3152 6401",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/tory-burch",
"top3": "sim",
"imagem": "sofisticadoF4"
},
{
"item": "Calça",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 348,00",
"preco": "acima de R$ 300,00",
"tipo": "Vestuário",
"descricao": "Calça de linho",
"estabelecimento": "Triton ",
"endereco": "Rua Oscar Freire, 993",
"telefone": "(11) 3085 9089",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/triton",
"top3": "não",
"imagem": "sofisticadoM3"
},
{
"item": "Calça",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 349,00",
"preco": "acima de R$ 300,00",
"tipo": "Vestuário",
"descricao": "Calça flare estampada",
"estabelecimento": "MoB - Shopping Anália Franco",
"endereco": "Avenida Regente Feijó, 1739",
"telefone": "(11) 2675 1633",
"bairro": "Vila Regente Feijó",
"link": "http://vejasp.abril.com.br/estabelecimento/mob-shopping-analia-franco",
"top3": "não",
"imagem": "sofisticadoF5"
},
{
"item": "Voo Panorâmico",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "R$ 350,00 por pessoa",
"preco": "acima de R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Helimarte",
"endereco": "Avenida Olavo Fontoura, 1078 - Aeroporto Campo de Marte",
"telefone": "(11) 2221 3200",
"bairro": "Santana",
"link": "http://vejasp.abril.com.br/estabelecimento/helimarte",
"top3": "não",
"imagem": "voo-panoramico"
},
{
"item": "Voo Panorâmico",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "R$ 350,00 por pessoa",
"preco": "acima de R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Helimarte",
"endereco": "Avenida Olavo Fontoura, 1078 - Aeroporto Campo de Marte",
"telefone": "(11) 2221 3200",
"bairro": "Santana",
"link": "http://vejasp.abril.com.br/estabelecimento/helimarte",
"top3": "não",
"imagem": "voo-panoramico"
},
{
"item": "Terraço Itália - Bar",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "R$ 390,00 por pessoa",
"preco": "acima de R$ 300,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Terraço Itália",
"endereco": "Avenida Ipiranga, 344 - 42º andar",
"telefone": "(11) 2189 2929",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/terraco-italia-bar",
"top3": "sim",
"imagem": "terraco-italia2"
},
{
"item": "Terraço Itália - Bar",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "R$ 390,00 por pessoa",
"preco": "acima de R$ 300,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Terraço Itália",
"endereco": "Avenida Ipiranga, 344 - 42º andar",
"telefone": "(11) 2189 2929",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/terraco-italia-bar",
"top3": "sim",
"imagem": "terraco-italia2"
},
{
"item": "Bolsa ",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 399,00 ",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Bolsa de couro nude",
"estabelecimento": "Colcci - Shopping Pátio Higienópolis ",
"endereco": "Avenida Higienópolis, 618",
"telefone": "(11) 3129 8111",
"bairro": "Higienópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/colcci-shopping-patio-higienopolis",
"top3": "sim",
"imagem": "basicoF5"
},
{
"item": "Lenço ",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 399,00 ",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Lenço de seda estampado",
"estabelecimento": "Sou Q",
"endereco": "Avenida Presidente Juscelino Kubitschek, 2041",
"telefone": "(11) 3777 7466",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/souq",
"top3": "sim",
"imagem": "sofisticadoF9"
},
{
"item": "Relógio",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 399,00 ",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Relógio de madeira",
"estabelecimento": "We Wood",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.wewoodbrasil.com.br/relogios",
"top3": "sim",
"imagem": "hipsterM1"
},
{
"item": "Cartão",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 45,00",
"preco": "até R$ 100,00",
"tipo": "Papelaria",
"descricao": "Cartão em formato de vinil",
"estabelecimento": "Casa 8 - Shopping Cidade Jardim",
"endereco": "Av. Magalhães de Castro, 12000",
"telefone": "(11) 3552 8888",
"bairro": "Morumbi",
"link": "http://vejasp.abril.com.br/estabelecimento/casa-8-shopping-cidade-jardim",
"top3": "sim",
"imagem": "hipsterM9"
},
{
"item": "Luvas",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 49,90",
"preco": "até R$ 100,00",
"tipo": "Acessório",
"descricao": "Luvas para academia",
"estabelecimento": "Miami Sports",
"endereco": "Avenida Água Fria, 1798",
"telefone": "(11) 2203-1597",
"bairro": "Água Fria",
"link": "http://vejasp.abril.com.br/estabelecimento/miami-sports",
"top3": "sim",
"imagem": "esportistaF4"
},
{
"item": "Câmera Fotográfica",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 499,00",
"preco": "acima de R$ 300,00",
"tipo": "Eletrônico",
"descricao": "Câmera Fotográfica Coolpix Nikon",
"estabelecimento": "Magazine Luiza - Santo Amaro",
"endereco": "Rua Capitão Tiago Luz, 57",
"telefone": "(11) 5545 6000",
"bairro": "Santo Amaro",
"link": "http://vejasp.abril.com.br/estabelecimento/magazine-luiza-santo-amaro",
"top3": "sim",
"imagem": "hipsterM6"
},
{
"item": "Vontade Construtiva na Coleção Fadel",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "R$ 6,00",
"preco": "até R$ 100,00",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Museu da Arte Moderna - MAM",
"endereco": "Parque Do Ibirapuera, s/nº",
"telefone": "(11) 5085 1300",
"bairro": "Parque Ibirapuera",
"link": "http://vejasp.abril.com.br/estabelecimento/museu-de-arte-moderna-mam",
"top3": "não",
"imagem": "vontade-construtiva"
},
{
"item": "Vontade Construtiva na Coleção Fadel",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "R$ 6,00",
"preco": "até R$ 100,00",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Museu da Arte Moderna - MAM",
"endereco": "Parque Do Ibirapuera, s/nº",
"telefone": "(11) 5085 1300",
"bairro": "Parque Ibirapuera",
"link": "http://vejasp.abril.com.br/estabelecimento/museu-de-arte-moderna-mam",
"top3": "não",
"imagem": "vontade-construtiva"
},
{
"item": "Relógio",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 649,00",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Relógio com pulseira emborrachada",
"estabelecimento": "Diesel para Daifiti",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.dafiti.com.br/",
"top3": "sim",
"imagem": "esportistaM4"
},
{
"item": "Boné",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 69,90",
"preco": "até R$ 100,00",
"tipo": "Acessório",
"descricao": "Boné de sarja",
"estabelecimento": "Mormaii",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.mormaiishop.com.br/",
"top3": "não",
"imagem": "esportistaM6"
},
{
"item": "Carteira",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 79,00",
"preco": "até R$ 100,00",
"tipo": "Acessório",
"descricao": "Carteira de couro",
"estabelecimento": "CNS - Shopping Tatuapé",
"endereco": "Rua Domingos Agostim, 91",
"telefone": "(11) 2092 9659",
"bairro": "Tatuapé",
"link": "http://vejasp.abril.com.br/estabelecimento/cns-shopping-tatuape",
"top3": "sim",
"imagem": "basicoM3"
},
{
"item": "Sapato",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 79,90",
"preco": "até R$ 100,00",
"tipo": "Calçado",
"descricao": "Sapatilha de vernis",
"estabelecimento": "Jorge Alex - Santana",
"endereco": "Rua Alfredo Pujol, 1269",
"telefone": "(11) 3321 7700",
"bairro": "Santana",
"link": "http://vejasp.abril.com.br/estabelecimento/jorge-alex",
"top3": "sim",
"imagem": "basicoF4"
},
{
"item": "Camiseta",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 89,90",
"preco": "até R$ 100,00",
"tipo": "Vestuário",
"descricao": "Camiseta estampada",
"estabelecimento": "TNG - Shopping Villa-Lobos",
"endereco": "Avenida Das Nações Unidas, 4777",
"telefone": "(11) 3024 3738",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/tng-shopping-villa-lobos",
"top3": "não",
"imagem": "esportistaF8"
},
{
"item": "Fones de ouvido",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 89,90",
"preco": "até R$ 100,00",
"tipo": "Eletrônico",
"descricao": "Fones de ouvido de pelúcia",
"estabelecimento": "UATT - Shopping Boulevard Metrô Tatuapé",
"endereco": "Rua Gonçalves Crespo, 78",
"telefone": "(11) 2225 7031",
"bairro": "Tatuapé",
"link": "http://vejasp.abril.com.br/estabelecimento/uatt",
"top3": "sim",
"imagem": "hipsterF7"
},
{
"item": "Camisa",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 99,00",
"preco": "até R$ 100,00",
"tipo": "Vestuário",
"descricao": "Camisa masculina slim fit",
"estabelecimento": "Memove ",
"endereco": "Rua Capitão Pachecoi e Chaves, 313",
"telefone": "(11) 2219 0288",
"bairro": "Mooca",
"link": "http://vejasp.abril.com.br/estabelecimento/memove",
"top3": "sim",
"imagem": "basicoM1"
},
{
"item": "Regata",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 99,90",
"preco": "até R$ 100,00",
"tipo": "Vestuário",
"descricao": "Regata dry fit",
"estabelecimento": "Gap - Shopping JK Iguatemi",
"endereco": "Avenida Presidente Juscelino Kubitschek, 2041",
"telefone": "(11) 3038 2527",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/gap-shopping-jk-iguatemi",
"top3": "não",
"imagem": "esportistaF2"
},
{
"item": "Camisa",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 99,95",
"preco": "até R$ 100,00",
"tipo": "Vestuário",
"descricao": "Camisa de flanela xadrez",
"estabelecimento": "Colombo - Shopping Bourbon",
"endereco": "Rua Turiassu, 2100",
"telefone": "(11) 3522 5743",
"bairro": "Perdizes",
"link": "http://vejasp.abril.com.br/estabelecimento/colombo-shopping-bourbon",
"top3": "não",
"imagem": "hipsterM8"
}
]
}