var dadosTop = {
"presentesTop" : [
{
"item": "Escalada Indoor",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 30,00",
"preco": "até R$ 100,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "90 Graus",
"endereco": "Avenida João Pedro Cardoso, 107",
"telefone": "(11) 5034 8775",
"bairro": "Parque Jabaquara",
"link": "http://vejasp.abril.com.br/estabelecimento/90-graus",
"top3": "sim",
"imagem": "escalada"
},
{
"item": "Escalada Indoor",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 30,00",
"preco": "até R$ 100,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "90 Graus",
"endereco": "Avenida João Pedro Cardoso, 107",
"telefone": "(11) 5034 8775",
"bairro": "Parque Jabaquara",
"link": "http://vejasp.abril.com.br/estabelecimento/90-graus",
"top3": "sim",
"imagem": "escalada"
},
{
"item": "Paraquedismo",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 410,00",
"preco": "acima de R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Hangar Vera Cruz",
"endereco": "Acesso de Campinas pela SP 340/344",
"telefone": "(19) 3246-0455",
"bairro": "São João da Boavista",
"link": "http://vejasp.abril.com.br/atracao/paraquedismo",
"top3": "sim",
"imagem": "paraquedismo"
},
{
"item": "Paraquedismo",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "a partir de R$ 410,00",
"preco": "acima de R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Hangar Vera Cruz",
"endereco": "Acesso de Campinas pela SP 340/344",
"telefone": "(19) 3246-0455",
"bairro": "São João da Boavista",
"link": "http://vejasp.abril.com.br/atracao/paraquedismo",
"top3": "sim",
"imagem": "paraquedismo"
},
{
"item": "Jun Sakamoto",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Jun Sakamoto",
"endereco": "Rua Lisboa, 55",
"telefone": "(11) 3088 6019",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/jun-sakamoto",
"top3": "sim",
"imagem": "jun-sakamoto"
},
{
"item": "Fasano",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Fasano",
"endereco": "Rua Vitório Fasano, 88",
"telefone": "(11) 3062 4000",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/fasano",
"top3": "sim",
"imagem": "fasano"
},
{
"item": "Terraço Itália",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Terraço Itália",
"endereco": "Avenida Ipiranga, 344",
"telefone": "(11) 2189 2929",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/terraco-italia",
"top3": "sim",
"imagem": "terraco-italia"
},
{
"item": "Jun Sakamoto",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Jun Sakamoto",
"endereco": "Rua Lisboa, 55",
"telefone": "(11) 3088 6019",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/jun-sakamoto",
"top3": "sim",
"imagem": "jun-sakamoto"
},
{
"item": "Fasano",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Fasano",
"endereco": "Rua Vitório Fasano, 88",
"telefone": "(11) 3062 4000",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/fasano",
"top3": "sim",
"imagem": "fasano"
},
{
"item": "Terraço Itália",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "acima de R$ 175,00",
"preco": "acima de R$ 175,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Terraço Itália",
"endereco": "Avenida Ipiranga, 344",
"telefone": "(11) 2189 2929",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/terraco-italia",
"top3": "sim",
"imagem": "terraco-italia"
},
{
"item": "Esquina Mocotó",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "até R$ 70,00",
"preco": "até R$ 70,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Esquina Mocotó",
"endereco": "Avenida Nossa Senhora do Loreto, 1108",
"telefone": "(11) 2949 7049",
"bairro": "Vila Medeiros",
"link": "http://vejasp.abril.com.br/estabelecimento/esquina-mocoto",
"top3": "sim",
"imagem": "esquina-mocoto"
},
{
"item": "Esquina Mocotó",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "até R$ 70,00",
"preco": "até R$ 70,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Esquina Mocotó",
"endereco": "Avenida Nossa Senhora do Loreto, 1108",
"telefone": "(11) 2949 7049",
"bairro": "Vila Medeiros",
"link": "http://vejasp.abril.com.br/estabelecimento/esquina-mocoto",
"top3": "sim",
"imagem": "esquina-mocoto"
},
{
"item": "Aya Japanese Cuisine",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Aya Japanese Cuisine",
"endereco": "Avenida Pedroso de Morais, 141",
"telefone": "(11) 3097 9856",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/aya-japanese-cuisine",
"top3": "sim",
"imagem": "aya-restaurante"
},
{
"item": "Naga",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Naga",
"endereco": "Rua Bandeira Paulista, 385",
"telefone": "(11) 3167 6049",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/naga",
"top3": "sim",
"imagem": "naga-restaurante"
},
{
"item": "Brasil a Gosto",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Brasil a Gosto",
"endereco": "Rua Professor Azevedo Amaral, 70",
"telefone": "(11) 3086 3565",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/brasil-gosto#6",
"top3": "sim",
"imagem": "brasil-a-gosto"
},
{
"item": "Dalva e Dito",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Dalva e Dito",
"endereco": "Rua Padre João Manuel, 1115",
"telefone": "(11) 3068 4444",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/dalva-dito",
"top3": "sim",
"imagem": "dalva-dito"
},
{
"item": "Ici Bistrô",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Ici Bistrô",
"endereco": "Rua Pará, 36",
"telefone": "(11) 3257 4064",
"bairro": "Higienópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/ici-bistro",
"top3": "sim",
"imagem": "ici-bristro"
},
{
"item": "La Casserole",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "La Casserole",
"endereco": "Largo Do Arouche, 346",
"telefone": "(11) 3331 6283",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/la-casserole",
"top3": "sim",
"imagem": "la-casserole"
},
{
"item": "Allez, Allez!",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Allez, Allez!",
"endereco": "Rua Wisard, 288",
"telefone": "(11) 3032 3325",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/allez-allez",
"top3": "sim",
"imagem": "allez-allez"
},
{
"item": "Aya Japanese Cuisine",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Aya Japanese Cuisine",
"endereco": "Avenida Pedroso de Morais, 141",
"telefone": "(11) 3097 9856",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/aya-japanese-cuisine",
"top3": "sim",
"imagem": "aya-restaurante"
},
{
"item": "Naga",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Asiática",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Asiático",
"descricao": "-",
"estabelecimento": "Naga",
"endereco": "Rua Bandeira Paulista, 385",
"telefone": "(11) 3167 6049",
"bairro": "Itaim Bibi",
"link": "http://vejasp.abril.com.br/estabelecimento/naga",
"top3": "sim",
"imagem": "naga-restaurante"
},
{
"item": "Brasil a Gosto",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Brasil a Gosto",
"endereco": "Rua Professor Azevedo Amaral, 71",
"telefone": "(11) 3086 3566",
"bairro": "Jardim Paulista",
"link": "http://vejasp.abril.com.br/estabelecimento/brasil-gosto#6",
"top3": "sim",
"imagem": "brasil-a-gosto"
},
{
"item": "Dalva e Dito",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Brasileira",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Brasileiro",
"descricao": "-",
"estabelecimento": "Dalva e Dito",
"endereco": "Rua Padre João Manuel, 1115",
"telefone": "(11) 3068 4444",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/dalva-dito",
"top3": "sim",
"imagem": "dalva-dito"
},
{
"item": "Ici Bistrô",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Ici Bistrô",
"endereco": "Rua Pará, 36",
"telefone": "(11) 3257 4064",
"bairro": "Higienópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/ici-bistro",
"top3": "sim",
"imagem": "ici-bristro"
},
{
"item": "La Casserole",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "La Casserole",
"endereco": "Largo Do Arouche, 346",
"telefone": "(11) 3331 6283",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/la-casserole",
"top3": "sim",
"imagem": "la-casserole"
},
{
"item": "Allez, Allez!",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Francesa",
"preco_exato": "de R$ 106,00 a R$ 175,00",
"preco": "de R$ 106,00 a R$ 175,00",
"tipo": "Francês",
"descricao": "-",
"estabelecimento": "Allez, Allez!",
"endereco": "Rua Wisard, 288",
"telefone": "(11) 3032 3325",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/allez-allez",
"top3": "sim",
"imagem": "allez-allez"
},
{
"item": "Motel Lush by Côncavo e Convexo",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "de R$ 210,00 a R$ 260,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Motel Lush by Côncavo e Convexo",
"endereco": "Avenida do Estado, 6600",
"telefone": "(11) 2274 7433",
"bairro": "Cambuci",
"link": "http://vejasp.abril.com.br/estabelecimento/lush-by-concavo-e-convexo",
"top3": "sim",
"imagem": "motel-lush"
},
{
"item": "Motel Lush by Côncavo e Convexo",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Sair da Rotina",
"preco_exato": "de R$ 210,00 a R$ 260,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Sair da Rotina",
"descricao": "-",
"estabelecimento": "Motel Lush by Côncavo e Convexo",
"endereco": "Avenida do Estado, 6600",
"telefone": "(11) 2274 7433",
"bairro": "Cambuci",
"link": "http://vejasp.abril.com.br/estabelecimento/lush-by-concavo-e-convexo",
"top3": "sim",
"imagem": "motel-lush"
},
{
"item": "Pinacoteca do Estado",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "de R$ 3,00 a R$ 6,00",
"preco": "até R$ 100,00",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Pinacoteca do Estado",
"endereco": "Praça Da Luz, 2",
"telefone": "(11) 3324 1000",
"bairro": "Bom Retiro",
"link": "http://vejasp.abril.com.br/estabelecimento/pinacoteca#2",
"top3": "sim",
"imagem": "pinaciteca"
},
{
"item": "Pinacoteca do Estado",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "de R$ 3,00 a R$ 6,00",
"preco": "até R$ 100,00",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Pinacoteca do Estado",
"endereco": "Praça Da Luz, 2",
"telefone": "(11) 3324 1000",
"bairro": "Bom Retiro",
"link": "http://vejasp.abril.com.br/estabelecimento/pinacoteca#2",
"top3": "sim",
"imagem": "pinaciteca"
},
{
"item": "Elis, A Musical",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 40,00 a R$ 140,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Teatro Alfa",
"endereco": "Rua Bento Branco De Andrade Filho, 722",
"telefone": "(11) 5693 4000",
"bairro": "Santo Amaro",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-alfa",
"top3": "sim",
"imagem": "elis-musical"
},
{
"item": "Elis, A Musical",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 40,00 a R$ 140,00",
"preco": "até R$ 100,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Teatro Alfa",
"endereco": "Rua Bento Branco De Andrade Filho, 722",
"telefone": "(11) 5693 4000",
"bairro": "Santo Amaro",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-alfa",
"top3": "sim",
"imagem": "elis-musical"
},
{
"item": "Djavan",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 70,00 a R$ 240,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Citibank Hall",
"endereco": "Avenida das Nações Unidas, 17955",
"telefone": "(11) 4003 5588",
"bairro": "Vila Almeida",
"link": "http://vejasp.abril.com.br/estabelecimento/citibank-hall",
"top3": "sim",
"imagem": "djavan"
},
{
"item": "Djavan",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "de R$ 70,00 a R$ 240,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Citibank Hall",
"endereco": "Avenida das Nações Unidas, 17955",
"telefone": "(11) 4003 5588",
"bairro": "Vila Almeida",
"link": "http://vejasp.abril.com.br/estabelecimento/citibank-hall",
"top3": "sim",
"imagem": "djavan"
},
{
"item": "Vito",
"sexo": "Feminino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Vito",
"endereco": "Rua Isabel De Castela, 529",
"telefone": "(11) 3032 1469",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/vito",
"top3": "sim",
"imagem": "vito"
},
{
"item": "Vito",
"sexo": "Masculino",
"categoria": "Restaurante",
"perfil": "Italiana",
"preco_exato": "de R$ 71,00 a R$ 105,00",
"preco": "de R$ 71,00 a R$ 105,00",
"tipo": "Italiano",
"descricao": "-",
"estabelecimento": "Vito",
"endereco": "Rua Isabel De Castela, 529",
"telefone": "(11) 3032 1469",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/vito",
"top3": "sim",
"imagem": "vito"
},
{
"item": "Passeio pelo Teatro Municipal",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Teatro Municipal",
"endereco": "Praça Ramos De Azevedo, s/nº -",
"telefone": "(11) 3397 0327",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-municipal",
"top3": "sim",
"imagem": "teatro-municipal"
},
{
"item": "Feira da Praça Benedito Calixto",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Praça Benedito Calixto",
"endereco": "Praça Benedito Calixto, 158/162",
"telefone": "(11) 3081 0641",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/feira-praca-benedito-calixto",
"top3": "sim",
"imagem": "benedito-calixo"
},
{
"item": "Yayoi Kusama",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Instituto Tomie Ohtake",
"endereco": "Rua Dos Coropés, 88",
"telefone": "(11) 2245 1900",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/instituto-tomie-ohtake-pinheiros",
"top3": "sim",
"imagem": "yayoi-kusama"
},
{
"item": "Jardim Botânico",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Jardim Botânico",
"endereco": "Avenida Miguel Estéfno, 3031",
"telefone": "(11) 5067 6049",
"bairro": "Saúde",
"link": "http://vejasp.abril.com.br/estabelecimento/jardim-botanico",
"top3": "sim",
"imagem": "jardim-botanico"
},
{
"item": "Praça do Por do Sol",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Praça Coronel Custódio Fernandes Pinheiros",
"endereco": "Rua Desembargador Ferreira França, S/N",
"telefone": "-",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/praca-cel-custodio-fernandes-pinheiros-por-do-sol",
"top3": "sim",
"imagem": "praca-por-sol"
},
{
"item": "Passeio pelo Teatro Municipal",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Teatro Municipal",
"endereco": "Praça Ramos De Azevedo, s/nº -",
"telefone": "(11) 3397 0327",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/teatro-municipal",
"top3": "sim",
"imagem": "teatro-municipal"
},
{
"item": "Feira da Praça Benedito Calixto",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Praça Benedito Calixto",
"endereco": "Praça Benedito Calixto, 158/162",
"telefone": "(11) 3081 0641",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/feira-praca-benedito-calixto",
"top3": "sim",
"imagem": "benedito-calixo"
},
{
"item": "Yayoi Kusama",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Arte",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Arte",
"descricao": "-",
"estabelecimento": "Instituto Tomie Ohtake",
"endereco": "Rua Dos Coropés, 88",
"telefone": "(11) 2245 1900",
"bairro": "Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/instituto-tomie-ohtake-pinheiros",
"top3": "sim",
"imagem": "yayoi-kusama"
},
{
"item": "Jardim Botânico",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Jardim Botânico",
"endereco": "Avenida Miguel Estéfno, 3031",
"telefone": "(11) 5067 6049",
"bairro": "Saúde",
"link": "http://vejasp.abril.com.br/estabelecimento/jardim-botanico",
"top3": "sim",
"imagem": "jardim-botanico"
},
{
"item": "Praça do Por do Sol",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Atividade ao ar livre",
"preco_exato": "Grátis",
"preco": "Grátis",
"tipo": "Atividade ao ar livre",
"descricao": "-",
"estabelecimento": "Praça Coronel Custódio Fernandes Pinheiros",
"endereco": "Rua Desembargador Ferreira França, S/N",
"telefone": "-",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/praca-cel-custodio-fernandes-pinheiros-por-do-sol",
"top3": "sim",
"imagem": "praca-por-sol"
},
{
"item": "Tênis",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 129,90",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Tênis com estampa de corações",
"estabelecimento": "Art Walk - Shopping Villa-Lobos",
"endereco": "Avenida das Nações Unidas, 4777",
"telefone": "(11) 3021 7329",
"bairro": "Alto de Pinheiros",
"link": "http://vejasp.abril.com.br/estabelecimento/artwalk-shopping-villa-lobos",
"top3": "sim",
"imagem": "hipsterF4"
},
{
"item": "Sapatênis",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 159,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Calçado",
"descricao": "Sapatênis de lona",
"estabelecimento": "Timberland para World Tennis - Shopping Bourbon",
"endereco": "Rua Turiassu, 2100",
"telefone": "(11) 3675 3481",
"bairro": "Perdizes",
"link": "http://vejasp.abril.com.br/estabelecimento/world-tennis-shopping-bourbon",
"top3": "sim",
"imagem": "basicoM4"
},
{
"item": "Gravata",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 179,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Gravata de seda listrada",
"estabelecimento": "Ricardo Almeida - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 2232",
"telefone": "(11) 3812 6947",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/ricardo-almeida-shopping-iguatemi",
"top3": "sim",
"imagem": "sofisticadoM2"
},
{
"item": "Chapéu",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 189,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Acessório",
"descricao": "Chapéu vermelho com laço",
"estabelecimento": "Accessorize - Jardins",
"endereco": "Rua Haddock Lobo, 1491 - Cerqueira César",
"telefone": "(11) 3061 5136",
"bairro": "Jardins",
"link": "http://vejasp.abril.com.br/estabelecimento/accessorize-jardins",
"top3": "sim",
"imagem": "hipsterF1"
},
{
"item": "Top",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 198,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Cropped top",
"estabelecimento": "John John - Oscar Freire",
"endereco": "Rua Oscar Freire, 798",
"telefone": "(11) 3061 9906",
"bairro": "Cerqueira César",
"link": "http://vejasp.abril.com.br/estabelecimento/john-john-denim",
"top3": "sim",
"imagem": "esportistaF3"
},
{
"item": "Calça",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 199,00",
"preco": "de R$ 100,00 a R$ 200,00",
"tipo": "Vestuário",
"descricao": "Calça de sarja colorida",
"estabelecimento": "Crawford - Shopping Morumbi",
"endereco": "Avenida Roque Petroni Júnior, 1089",
"telefone": "(11) 5189 4609",
"bairro": "Jardim das Acácias",
"link": "http://vejasp.abril.com.br/estabelecimento/crawford-shopping-morumbi",
"top3": "sim",
"imagem": "sofisticadoM6"
},
{
"item": "Abotoadoras",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 219,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Abotoadoras de metal",
"estabelecimento": "Aramis - Shopping Bourbon",
"endereco": "Rua Turiassu, 2100",
"telefone": "(11) 3892 4313",
"bairro": "Perdizes",
"link": "http://vejasp.abril.com.br/estabelecimento/aramis-shopping-bourbon",
"top3": "sim",
"imagem": "sofisticadoM1"
},
{
"item": "Jaqueta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 221,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Jaqueta esportiva",
"estabelecimento": "Lupo - Jardins",
"endereco": "Alameda Lorena, 1647",
"telefone": "(11) 3081 4833",
"bairro": "Jardim Paulista ",
"link": "http://vejasp.abril.com.br/estabelecimento/lupo-jardins",
"top3": "sim",
"imagem": "esportistaM3"
},
{
"item": "Camiseta",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 229,90",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Camiseta oficial da Seleção Brasileira",
"estabelecimento": "Centauro - Shopping Center Norte",
"endereco": "Travessa Casalbuono, 120",
"telefone": "(11) 2221 1771",
"bairro": "Vila Guilherme",
"link": "http://vejasp.abril.com.br/estabelecimento/centauro-shopping-center-norte",
"top3": "sim",
"imagem": "esportistaM7"
},
{
"item": "Blusa",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 279,90",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Vestuário",
"descricao": "Blusa de cetim",
"estabelecimento": "OQVestir",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.oqvestir.com.br/",
"top3": "sim",
"imagem": "basicoF8"
},
{
"item": "Pulseira",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 295,00",
"preco": "de R$ 200,00 a R$ 300,00",
"tipo": "Acessório",
"descricao": "Bracelete com cristais Swarovski",
"estabelecimento": "Swarovski - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 2232",
"telefone": "(11) 3816 7111",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/swarovski-shopping-iguatemi",
"top3": "sim",
"imagem": "sofisticadoF1"
},
{
"item": "Tênis",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 300,00",
"preco": "acima de R$ 300,00",
"tipo": "Calçado",
"descricao": "Tênis Faas Puma",
"estabelecimento": "Puma",
"endereco": "E-commerce",
"telefone": "",
"bairro": "",
"link": "http://shop.brasil.puma.com/",
"top3": "sim",
"imagem": "esportistaF1"
},
{
"item": "Nécessaire",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 310,00",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Nécessaire estampada",
"estabelecimento": "Tory Burch - Shopping Iguatemi",
"endereco": "Avenida Brigadeiro Faria Lima, 2232",
"telefone": "(11) 3152 6401",
"bairro": "Jardim Paulistano",
"link": "http://vejasp.abril.com.br/estabelecimento/tory-burch",
"top3": "sim",
"imagem": "sofisticadoF4"
},
{
"item": "Terraço Itália - Bar",
"sexo": "Feminino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "R$ 390,00 por pessoa",
"preco": "acima de R$ 300,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Terraço Itália",
"endereco": "Avenida Ipiranga, 344 - 42º andar",
"telefone": "(11) 2189 2929",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/terraco-italia-bar",
"top3": "sim",
"imagem": "terraco-italia2"
},
{
"item": "Terraço Itália - Bar",
"sexo": "Masculino",
"categoria": "Passeio",
"perfil": "Música",
"preco_exato": "R$ 390,00 por pessoa",
"preco": "acima de R$ 300,00",
"tipo": "Música",
"descricao": "-",
"estabelecimento": "Terraço Itália",
"endereco": "Avenida Ipiranga, 344 - 42º andar",
"telefone": "(11) 2189 2929",
"bairro": "República",
"link": "http://vejasp.abril.com.br/estabelecimento/terraco-italia-bar",
"top3": "sim",
"imagem": "terraco-italia2"
},
{
"item": "Bolsa ",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 399,00 ",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Bolsa de couro nude",
"estabelecimento": "Colcci - Shopping Pátio Higienópolis ",
"endereco": "Avenida Higienópolis, 618",
"telefone": "(11) 3129 8111",
"bairro": "Higienópolis",
"link": "http://vejasp.abril.com.br/estabelecimento/colcci-shopping-patio-higienopolis",
"top3": "sim",
"imagem": "basicoF5"
},
{
"item": "Lenço ",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Sofisticado",
"preco_exato": "R$ 399,00 ",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Lenço de seda estampado",
"estabelecimento": "Sou Q",
"endereco": "Avenida Presidente Juscelino Kubitschek, 2041",
"telefone": "(11) 3777 7466",
"bairro": "Vila Nova Conceição",
"link": "http://vejasp.abril.com.br/estabelecimento/souq",
"top3": "sim",
"imagem": "sofisticadoF9"
},
{
"item": "Relógio",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 399,00 ",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Relógio de madeira",
"estabelecimento": "We Wood",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.wewoodbrasil.com.br/relogios",
"top3": "sim",
"imagem": "hipsterM1"
},
{
"item": "Cartão",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 45,00",
"preco": "até R$ 100,00",
"tipo": "Papelaria",
"descricao": "Cartão em formato de vinil",
"estabelecimento": "Casa 8 - Shopping Cidade Jardim",
"endereco": "Av. Magalhães de Castro, 12000",
"telefone": "(11) 3552 8888",
"bairro": "Morumbi",
"link": "http://vejasp.abril.com.br/estabelecimento/casa-8-shopping-cidade-jardim",
"top3": "sim",
"imagem": "hipsterM9"
},
{
"item": "Luvas",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 49,90",
"preco": "até R$ 100,00",
"tipo": "Acessório",
"descricao": "Luvas para academia",
"estabelecimento": "Miami Sports",
"endereco": "Avenida Água Fria, 1798",
"telefone": "(11) 2203-1597",
"bairro": "Água Fria",
"link": "http://vejasp.abril.com.br/estabelecimento/miami-sports",
"top3": "sim",
"imagem": "esportistaF4"
},
{
"item": "Câmera Fotográfica",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 499,00",
"preco": "acima de R$ 300,00",
"tipo": "Eletrônico",
"descricao": "Câmera Fotográfica Coolpix Nikon",
"estabelecimento": "Magazine Luiza - Santo Amaro",
"endereco": "Rua Capitão Tiago Luz, 57",
"telefone": "(11) 5545 6000",
"bairro": "Santo Amaro",
"link": "http://vejasp.abril.com.br/estabelecimento/magazine-luiza-santo-amaro",
"top3": "sim",
"imagem": "hipsterM6"
},
{
"item": "Relógio",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Esportista",
"preco_exato": "R$ 649,00",
"preco": "acima de R$ 300,00",
"tipo": "Acessório",
"descricao": "Relógio com pulseira emborrachada",
"estabelecimento": "Diesel para Daifiti",
"endereco": "E-commerce",
"telefone": "-",
"bairro": "-",
"link": "http://www.dafiti.com.br/",
"top3": "sim",
"imagem": "esportistaM4"
},
{
"item": "Carteira",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 79,00",
"preco": "até R$ 100,00",
"tipo": "Acessório",
"descricao": "Carteira de couro",
"estabelecimento": "CNS - Shopping Tatuapé",
"endereco": "Rua Domingos Agostim, 91",
"telefone": "(11) 2092 9659",
"bairro": "Tatuapé",
"link": "http://vejasp.abril.com.br/estabelecimento/cns-shopping-tatuape",
"top3": "sim",
"imagem": "basicoM3"
},
{
"item": "Sapato",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 79,90",
"preco": "até R$ 100,00",
"tipo": "Calçado",
"descricao": "Sapatilha de vernis",
"estabelecimento": "Jorge Alex - Santana",
"endereco": "Rua Alfredo Pujol, 1269",
"telefone": "(11) 3321 7700",
"bairro": "Santana",
"link": "http://vejasp.abril.com.br/estabelecimento/jorge-alex",
"top3": "sim",
"imagem": "basicoF4"
},
{
"item": "Fones de ouvido",
"sexo": "Feminino",
"categoria": "Presente",
"perfil": "Hipster",
"preco_exato": "R$ 89,90",
"preco": "até R$ 100,00",
"tipo": "Eletrônico",
"descricao": "Fones de ouvido de pelúcia",
"estabelecimento": "UATT - Shopping Boulevard Metrô Tatuapé",
"endereco": "Rua Gonçalves Crespo, 78",
"telefone": "(11) 2225 7031",
"bairro": "Tatuapé",
"link": "http://vejasp.abril.com.br/estabelecimento/uatt",
"top3": "sim",
"imagem": "hipsterF7"
},
{
"item": "Camisa",
"sexo": "Masculino",
"categoria": "Presente",
"perfil": "Básico",
"preco_exato": "R$ 99,00",
"preco": "até R$ 100,00",
"tipo": "Vestuário",
"descricao": "Camisa masculina slim fit",
"estabelecimento": "Memove ",
"endereco": "Rua Capitão Pachecoi e Chaves, 313",
"telefone": "(11) 2219 0288",
"bairro": "Mooca",
"link": "http://vejasp.abril.com.br/estabelecimento/memove",
"top3": "sim",
"imagem": "basicoM1"
}
]
}